### PR TITLE
Add BERT driver method

### PR DESCRIPTION
**Pull request by Ashutosh-Adhikari**
Add the main file for functional trainer, evaluator.

### CODE REVIEW

**Comment by achyudh** [comment]
@Ashutosh-Adhikari I'll wait for your changes on the data loader before I go ahead and merge this. That would give us a better idea of how we would need to change the driver method.

**Comment by Ashutosh-Adhikari** [comment]
Sure!

**Review by achyudh — CHANGES_REQUESTED** [review]
As we discussed yesterday, the tokenization module is already present in https://github.com/karkaroff/hedwig/blob/bellatrix/models/bert/tokenizer.py. Can you please remove the duplicate datasets/tokenization4bert.py from the dataset folder?

**Review by achyudh — CHANGES_REQUESTED** [review]
Can you remove the file_utils.py file which you have added, as we already have the same methods in https://github.com/karkaroff/hedwig/blob/bellatrix/utils/io.py

**Comment by Ashutosh-Adhikari** [comment]
Sure! Thank you.

**Review by achyudh — APPROVED** [review]

**Comment by achyudh** [comment]
LGTM! Thanks for the pull request. 

We may have to refactor some things but I suppose that's not the priority right now.

**Pull request merged**
